language: node_js
cache:
  yarn: true
script: false
jobs:
  include:
    - stage: test
      if: branch = master
      node_js: '8.3'
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: test
      if: branch = master
      node_js: 'node'
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: test
      node_js: 'lts/*'
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: Integration Test
      if: branch = master
      node_js: 'lts/*'
      env:
        - TEST_BROWSERS_PATTERN="chrome"
      script:
        - yarn test-browsers
        - yarn test
        - yarn build
    - stage: Publish
      if: branch = master
      node_js: lts/*
      script: false
      deploy:
        provider: script
        script:
          - yarn run semantic-release
        skip_cleanup: true
        on:
          branch: master
