language: node_js
cache:
  yarn: true
node_js:
  - '8.3'
  - 'lts/*'
  - 'node'
script: false
jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: Publish
      node_js: lts/*
      script: false
      deploy:
        provider: script
        script:
          - yarn run semantic-release -- --dry-run
        skip_cleanup: true
        on:
          branch: master
