language: node_js
cache:
  yarn: true
script: false
jobs:
  include:
    - stage: test
      if: branch = master
      node_js: 'node'
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: test
      node_js: 'lts/*'
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: Publish
      if: branch = master
      node_js: lts/*
      script: false
      install: skip
      deploy:
        provider: script
        script:
          - yarn run semantic-release
        skip_cleanup: true
        on:
          branch: master
